IHM hot fix try to watch logs )(13)

diff --git a/.github/workflows/my-test.yml b/.github/workflows/my-test.yml
--- a/.github/workflows/my-test.yml
+++ b/.github/workflows/my-test.yml
@@ -48,3 +48,32 @@ jobs:
         run: |
           echo "===== Hub Router Logs ====="
           cat ./logs/hub-router.log || echo "Hub Router log not found"
+download-logs:  # <-- вот это наш новый job
+  needs: run-tests
+  runs-on: ubuntu-latest
+  if: ${{ inputs.print_logs == 'true' }}
+  steps:
+    - name: Checkout repo
+      uses: actions/checkout@v3
+
+    - name: Download Analyzer log artifact
+      uses: actions/download-artifact@v3
+      with:
+        name: analyzer-log
+        path: ./logs
+
+    - name: Download Hub Router log artifact
+      uses: actions/download-artifact@v3
+      with:
+        name: hub-router-log
+        path: ./logs
+
+    - name: Show Analyzer log
+      run: |
+        echo "===== Analyzer Logs ====="
+        cat ./logs/analyzer.log || echo "Analyzer log not found"
+
+    - name: Show Hub Router log
+      run: |
+        echo "===== Hub Router Logs ====="
+        cat ./logs/hub-router.log || echo "Hub Router log not found"
